
-- ==========================================
-- ProjectFlow DB Update v2: Dynamic Engines
-- ==========================================

-- 1. Knowledge Graph Tables
CREATE TABLE IF NOT EXISTS public.app_kb_nodes (
    id text PRIMARY KEY,
    label text NOT NULL,
    category text DEFAULT 'Concept', -- 'Core', 'Area', 'Process', 'Tool'
    description text,
    formula text, -- Optional markdown for formulas
    val int DEFAULT 40, -- Visual size
    course_id text REFERENCES public.app_courses(id) ON DELETE SET NULL, -- Link to a course
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.app_kb_edges (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source text REFERENCES public.app_kb_nodes(id) ON DELETE CASCADE,
    target text REFERENCES public.app_kb_nodes(id) ON DELETE CASCADE,
    type text -- Relationship label (e.g. 'contains', 'input_to')
);

-- 2. Simulation Script Support
-- Add a JSONB column to store the scenario script (events, choices, outcomes)
DO $$
BEGIN
    ALTER TABLE public.app_courses ADD COLUMN IF NOT EXISTS simulation_data jsonb DEFAULT '[]'::jsonb;
END $$;

-- 3. Enable RLS
ALTER TABLE public.app_kb_nodes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Access KB Nodes" ON public.app_kb_nodes;
CREATE POLICY "Public Access KB Nodes" ON public.app_kb_nodes FOR ALL USING (true);

ALTER TABLE public.app_kb_edges ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Access KB Edges" ON public.app_kb_edges;
CREATE POLICY "Public Access KB Edges" ON public.app_kb_edges FOR ALL USING (true);

-- 4. Seed Some Initial KG Data (Optional)
INSERT INTO public.app_kb_nodes (id, label, category, val, description)
VALUES 
('node-1', '项目整合管理', 'Core', 80, '项目管理的核心，负责协调各个过程组。'),
('node-2', '范围管理', 'Area', 60, '确保项目做且只做成功完成项目所需的全部工作。'),
('node-3', 'WBS (工作分解)', 'Tool', 45, '将项目可交付成果和项目工作分解成较小的、更易于管理的组件。')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.app_kb_edges (source, target, type)
VALUES ('node-1', 'node-2', 'includes'), ('node-2', 'node-3', 'uses')
ON CONFLICT DO NOTHING;
