
-- 1. Create Comments Table
CREATE TABLE IF NOT EXISTS public.app_comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id bigint REFERENCES public.app_community_posts(id) ON DELETE CASCADE,
    user_id text REFERENCES public.app_users(id) ON DELETE CASCADE,
    user_name text,
    user_avatar text,
    content text NOT NULL,
    likes int DEFAULT 0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 2. RLS Policies
ALTER TABLE public.app_comments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Access Comments" ON public.app_comments;
CREATE POLICY "Public Access Comments" ON public.app_comments FOR ALL USING (true);

-- 3. Add 'role' to comments for extra context (optional but good for UI)
DO $$
BEGIN
    ALTER TABLE public.app_comments ADD COLUMN IF NOT EXISTS role text DEFAULT 'Student';
END $$;
